{{--<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>--}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
<script src="{{ asset('dashboard/lib/chart/chart.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/easing/easing.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/waypoints/waypoints.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/owlcarousel/owl.carousel.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/tempusdominus/js/moment.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/tempusdominus/js/moment-timezone.min.js') }}"></script>
<script src="{{ asset('dashboard/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js') }}"></script>